# fly.toml app configuration file generated for sdr-db-api on 2025-12-12T16:22:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sdr-db-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  ALLOWED_ORIGINS = 'http://localhost:8080,https://sdr-db-website.vercel.app'
  API_PORT = '3000'
  RUST_LOG = 'info,api=debug'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
